from Locators.ReadExcelCellValue import read_data_from_excel


class get__home_page_locator_value:
    HOME_TAB = read_data_from_excel("HomePage", 2, 2)
    RIGHT_ARROW_BUTTON = read_data_from_excel("HomePage", 3, 2)
    LOGOUT_TAB = read_data_from_excel("HomePage", 4, 2)
    PATRON_TAB = read_data_from_excel("HomePage", 5, 2)
    SEARCH_PATRON = read_data_from_excel("HomePage", 6, 2)
    SEARCH_BUTTON = read_data_from_excel("HomePage", 7, 2)
    SEARCH_INPUT_BOX = read_data_from_excel("HomePage", 8, 2)
    NURSE_TRACKING = read_data_from_excel("HomePage", 9, 2)
    QUICK_APPS = read_data_from_excel("HomePage", 10, 2)
    FORMS = read_data_from_excel("HomePage", 11, 2)
    SCHOOL_PROGRAMS = read_data_from_excel("HomePage", 12, 2)

    FIRST_PATRON = read_data_from_excel("ViewPatron", 2, 2)
    QUICK_LUNCH_RESTRICTION = read_data_from_excel("ViewPatron", 3, 2)
    DAILY_SPEND_LIMIT = read_data_from_excel("ViewPatron", 4, 2)
    NO_A_LA_CARTE = read_data_from_excel("ViewPatron", 5, 2)
    NO_BREAKFAST = read_data_from_excel("ViewPatron", 6, 2)
    NO_SECOND_MEAL = read_data_from_excel("ViewPatron", 7, 2)
    ITEM_GROUPS_NOT_ALLOWED_LIST = read_data_from_excel("ViewPatron", 8, 2)
    ITEMS_NOT_ALLOWED_LIST = read_data_from_excel("ViewPatron", 9, 2)
    ITEM_GROUP_NOT_ALLOWED = read_data_from_excel("ViewPatron", 10, 2)
    ITEMS_NOT_ALLOWED = read_data_from_excel("ViewPatron", 11, 2)
    REPORTS = read_data_from_excel("ViewPatron", 12, 2)
    PATRON = read_data_from_excel("ViewPatron", 13, 2)
    ACCOUNT_REPORT = read_data_from_excel("ViewPatron", 14, 2)
    PATRON_ACCOUNT_ACTIVITY = read_data_from_excel("ViewPatron", 15, 2)
    PATRON_BUTTON = read_data_from_excel("ViewPatron", 16, 2)
    LAST_NAME = read_data_from_excel("ViewPatron", 17, 2)
    FIRST_NAME = read_data_from_excel("ViewPatron", 18, 2)
    SEARCH_TAB = read_data_from_excel("ViewPatron", 19, 2)
    ADD_ALL = read_data_from_excel("ViewPatron", 20, 2)
